### ISSUE TITLE
bug: image name mismatch between upstream and `cartographer.yaml` 

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/package-for-cartographer#11]
### problem

despite the proper setup of `.imgpkg/images.yml`, given that we're baking into the bundle a `cartographer.yaml` that is not matching the `images.yml` mapping

```
---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: projectcartographer/cartographer@sha256:c51ca0d715e73cb6126404d529147f8c05e1bbf0d14124f18124762f3a84b6a1
  image: index.docker.io/projectcartographer/package-for-cartographer@sha256:c51ca0d715e73cb6126404d529147f8c05e1bbf0d14124f18124762f3a84b6a1
kind: ImagesLock
```

because the `cartographer.yaml` included referred to ` index.docker.io/projectcartographer/package-for-cartographer@sha256:c51ca0d715e73cb6126404d529147f8c05e1bbf0d14124f18124762f3a84b6a1` rather than `projectcartographer/cartographer@sha256:c51ca0d715e73cb6126404d529147f8c05e1bbf0d14124f18124762f3a84b6a1`, no matches would occur.

### desired result

```
    Stderr:     resolve | final: projectcartographer/cartographer@sha256:c51ca0d715e73cb6126404d529147f8c05e1bbf0d14124f18124762f3a84b6a1 -> ghcr.io/cirocosta/cartographer@sha256:c51ca0d715e73cb6126404d529147f8c05e1bbf0d14124f18124762f3a84b6a1
```
