### ISSUE TITLE
address aks phantom diffs

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/package-for-cartographer#19]
```
#@ load("@ytt:overlay", "overlay")

#@ mutating_webhook = overlay.subset({"apiVersion": "admissionregistration.k8s.io/v1", "kind": "MutatingWebhookConfiguration"})
#@ validating_webhook = overlay.subset({"apiVersion": "admissionregistration.k8s.io/v1", "kind": "ValidatingWebhookConfiguration"})

#@overlay/match by=overlay.or_op(mutating_webhook,validating_webhook), expects="0+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    admissions.enforcer/disabled: "true"
```
