### ISSUE TITLE
packaging of multiple projects, for multiple targets

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/package-for-cartographer#27]
### problem

aiming at multiple distributions (OSS, TCE, TAP) and multiple projects
(cartographer and cartographer-catalog), it's hard to have under the assets
section of a GitHub release a well-named `package.yaml` and `metadata.yaml`
that covers all those cases given that we need to produce multiple of those.

regardless of how many projects we want to package (i.e., regardless of how
many directories we have under `./src/*` to create Packages for), given the
distributions we aim at releasing for we always face the problem of generating
two packages for each as:

1. the domain used for the package names is different
  - TCE: cartographer.**community.tanzu.vmware.com**
  - TAP: cartographer.**tanzu.vmware.com**

2. the registries where bundles are pushed to is different
  - TCE: `projects.registry.tanzu.vmware.com/tce/cartographer`

  - TAP: `index.docker.io/projectcartographer/cartographer` (so, anyone can
    consume and before releasing TAP, relocated to an internal VMware-hosted
    registry)

so, e.g., assuming we have `cartographer-catalog` already in and we want to
make it available for both TCE and "at-wide" (OSS in general), we'd end up with:

```
cartographer
        package.yaml    (cartographer.tanzu.vmware.com, dockerhub)
        metadata.yaml   (cartographer.tanzu.vmware.com)
        bundle.tar
        README.md

cartographer-tce
        package.yaml    (cartographer.community.tanzu.vmware.com, vmware registry)
        metadata.yaml   (cartographer.community.tanzu.vmware.com)
        bundle.tar      same as `cartographer`
        README.md       same as `cartographer`

cartographer-catalog
        package.yaml    (cartographer.tanzu.vmware.com, dockerhub)
        metadata.yaml   (cartographer.tanzu.vmware.com)
        bundle.tar
        README.md

cartographer-catalog-tce
        package.yaml    (cartographer.community.tanzu.vmware.com, vmware registry)
        metadata.yaml   (cartographer.community.tanzu.vmware.com)
        bundle.tar      same as `cartographer-catalog`
        README.md       same as `cartographer-catalog`
```

### proposed solution

to address the problem of making multiple assets available for the releases, I
propose that when doing so, rather than making the files (like, `package.yaml`)
directly available as an asset to be downloaded, instead have a `.tgz` for each
one of those directories I listed above - effectively:

```
cartographer.tgz
        '- package.yaml (cartographer.tanzu.vmware.com, dockerhub)
        '- metadata.yaml        (cartographer.tanzu.vmware.com)
        '- bundle.tar
        '- README.md

cartographer-tce.tgz
        '- package.yaml (cartographer.community.tanzu.vmware.com, vmware registry)
        '- metadata.yaml        (cartographer.community.tanzu.vmware.com)
        '- bundle.tar   same as `cartographer`
        '- README.md    same as `cartographer`

cartographer-catalog.tgz
        '- package.yaml (cartographer.tanzu.vmware.com, dockerhub)
        '- metadata.yaml        (cartographer.tanzu.vmware.com)
        '- bundle.tar
        '- README.md

cartographer-catalog-tce.tgz
        '- package.yaml (cartographer.community.tanzu.vmware.com, vmware registry)
        '- metadata.yaml        (cartographer.community.tanzu.vmware.com)
        '- bundle.tar   same as `cartographer-catalog`
        '- README.md    same as `cartographer-catalog`
```

### alternatives

one alternative I considered was prefixing the files with the target, like:

```
cartographer-package.yaml       (cartographer.tanzu.vmware.com, dockerhub)
cartographer-metadata.yaml      (cartographer.tanzu.vmware.com)
cartographer-bundle.tar
cartographer-README.md

cartographer-tce-package.yaml   (cartographer.community.tanzu.vmware.com, vmware registry)
cartographer-tce-metadata.yaml  (cartographer.community.tanzu.vmware.com)
cartographer-tce-bundle.tar     same as `cartographer`
cartographer-tce-README.md      same as `cartographer`
...
```

but the problem there is that systems that leverage `vendir` (e.g., TCE's
repository) wouldn't be happy about those file names as they'd diverge from
what's expected for their directory structure
(`addons/packages/<product>/<version>/package.yaml`) - having a compressed
tarball instead, we're able to, for each distribution, to point at the
appropriate tgz and unpack the files we care about in the right place, e.g.:

```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
  - path: 0.3.0
    contents:
      - path: .

        # 1. pick the release of `package-for-cartographer` for the tag v0.3.0
        #
        githubRelease:
          slug: vmware-tanzu/package-for-cartographer
          tag: v0.3.0
          disableAutoChecksumValidation: true

          # 2. unpack the tgz that's relevant for this pkg for TCE
          #
          unpackArchive:
            path: cartographer-catalog-tce.tgz

        # 3. from that tgz, just gather `package.yaml` and `README.md` as we
        #    don't need anything else from it.
        #
        includePaths:
          - README.md
          - package.yaml
```
