### ISSUE TITLE
configurable log level

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/package-for-cartographer#30]
### problem

cartographer allows one to configure the log level via the `-log-level` flag, but we currently miss a property in the package that would allow one to tweak that.

### proposed solution

add a property named `log_level: <default: "">` that would be used by the package to mutate the controller container to specify the `-log-level` flag.

for such, we could make use of an overlay like

```yaml
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "cartographer-controller"}})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by="name"
      - name: cartographer-controller
        args:
          - -log-level=#@ data.values.log_level
```

### acceptance

installing the cartographer package with specifying `log-level`:
  - with a value outside the enum we expect (info|debug|error): refuses to proceed w/ installation (fail at ytt level?)
  - with a good value specified, the container indeed takes the value in the right place
